-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (SUM(B.AMOUNT)*A.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT as A
JOIN FOOD_ORDER as B on A.PRODUCT_ID = B.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' and '2022-05-31'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC