-- 코드를 입력하세요
WITH TEMP as (
SELECT *
FROM FOOD_ORDER 
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
    )
    
SELECT B.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT*B.PRICE) as TOTAL_SALES
FROM TEMP as a
JOIN FOOD_PRODUCT as b on A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID, B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID ASC