-- 코드를 입력하세요
SELECT HOUR(DATETIME) as HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS 
WHERE DATE_FORMAT(DATETIME,'%H:%M:%s') BETWEEN '09:00:00' and '20:00:00'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)
