-- 코드를 입력하세요
WITH TEMP as (
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE('%Intact%')
    )
    
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE (SEX_UPON_OUTCOME LIKE('%Spayed%') or SEX_UPON_OUTCOME LIKE('%Neutered%'))
    AND ANIMAL_ID in (SELECT ANIMAL_ID FROM TEMP)
ORDER BY ANIMAL_ID