-- 코드를 작성해주세요
WITH CODES as (
SELECT B.CODE
FROM SKILLCODES as B
WHERE B.CATEGORY = 'Front End'
)



SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS as A
JOIN CODES AS B on A.SKILL_CODE & B.CODE > 0
ORDER BY A.ID ASC
