-- 코드를 작성해주세요
WITH F_SKILL as (
    SELECT CODE as SKILL_CODE
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS as D
JOIN F_SKILL as F on (D.SKILL_CODE & F.SKILL_CODE) > 0
ORDER BY D.ID
