-- 코드를 작성해주세요
WITH TEMP as (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE('%Front End%')
)

SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
JOIN TEMP AS B on A.SKILL_CODE & B.CODE > 0
ORDER BY A.ID ASC