-- 코드를 입력하세요

WITH REVIEWS as (
SELECT MEMBER_ID, COUNT(MEMBER_ID) as COUNT
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY COUNT DESC
limit 1
)

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE  as A
JOIN REST_REVIEW as B on A.MEMBER_ID = B.MEMBER_ID
JOIN REVIEWS as C on A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE ASC, B.REVIEW_TEXT ASC