-- 코드를 입력하세요
WITH TEMP as (
SELECT MEMBER_ID, COUNT(MEMBER_ID) as TOTAL
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY TOTAL DESC
LIMIT 1
    )
    
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
FROM MEMBER_PROFILE as A
JOIN REST_REVIEW as B on A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (SELECT MEMBER_ID FROM TEMP)
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC