-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE as A
JOIN REST_REVIEW  as B on A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID in
(
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(cnt) as cnt
        FROM (
            SELECT MEMBER_ID, COUNT(*) as cnt
            FROM REST_REVIEW 
            GROUP BY MEMBER_ID
            ) as T
        )
)
ORDER BY REVIEW_DATE ASC, B.REVIEW_TEXT ASC