-- 코드를 입력하세요
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID in (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '세단'
) and DATE_FORMAT(START_DATE,'%m-%d') BETWEEN '10-01' and '10-31'
ORDER BY CAR_ID DESC