-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as A
JOIN CAR_RENTAL_COMPANY_CAR as B on A.CAR_ID = B.CAR_ID
WHERE MONTH(A.START_DATE) = '10' and B.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC