-- 코드를 입력하세요
WITH TEMP as(
SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY in ( '과자', '국', '김치', '식용유')
GROUP BY CATEGORY
    )
    

SELECT A.CATEGORY,B.MAX_PRICE,A.PRODUCT_NAME
FROM FOOD_PRODUCT as A 
JOIN TEMP as B on A.CATEGORY = B.CATEGORY
WHERE A.PRICE = B.MAX_PRICE
ORDER BY B.MAX_PRICE DESC