-- 코드를 입력하세요

WITH MAX_TABLE as (
SELECT CATEGORY, max(PRICE) as MAX_PRICE
FROM FOOD_PRODUCT 
GROUP BY CATEGORY
    )
    
    
SELECT DISTINCT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT as A
JOIN MAX_TABLE as B on A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY in ('과자','국','김치','식용유')
ORDER BY A.PRICE DESC