-- 코드를 입력하세요
# SELECT (*)
# FROM FOOD_PRODUCT as p
# JOIN (
# SELECT CATEGORY, max(PRICE) as MAX_PRICE
# FROM FOOD_PRODUCT
# WHERE CATEGORY in ('과자','국','김치','식용유')
# GROUP BY CATEGORY
#     ) as t on p.CATEGORY = t.CATEGORY
SELECT 
    f.CATEGORY,
    f.PRICE AS MAX_PRICE,
    f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) t
ON f.CATEGORY = t.CATEGORY AND f.PRICE = t.MAX_PRICE
WHERE f.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY f.PRICE DESC;
