-- 코드를 입력하세요
WITH TEMP as (
SELECT CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31'
GROUP BY CAR_ID
    )
    
SELECT MONTH(A.START_DATE) as MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as A
JOIN TEMP as B on A.CAR_ID = B.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31' and B.RECORDS >= 5
GROUP BY MONTH, A.CAR_ID
ORDER BY MONTH ASC, A.CAR_ID DESC