#
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID in (SELECT B.ITEM_ID
FROM ITEM_INFO as A
JOIN ITEM_TREE  as B on A.ITEM_ID = B.PARENT_ITEM_ID
WHERE A.RARITY = 'RARE')
ORDER BY ITEM_ID DESC