-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as `YEAR`, MONTH(SALES_DATE) as `MONTH`, B.GENDER, COUNT(DISTINCT A.USER_ID) as USERS
FROM ONLINE_SALE as A
JOIN USER_INFO as B on A.USER_ID = B.USER_ID
WHERE B.GENDER IS NOT NULL
GROUP BY `YEAR`,`MONTH`,B.GENDER
ORDER BY `YEAR`,`MONTH`,B.GENDER
# GROUP BY `YEAR`, `MONTH`