-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, A.GENDER, COUNT(DISTINCT B.USER_ID) as USERS
FROM USER_INFO as A
JOIN ONLINE_SALE as B on A.USER_ID = B.USER_ID
WHERE GENDER in (0,1)
GROUP BY YEAR,MONTH,A.GENDER
ORDER BY YEAR,MONTH,A.GENDER ASC
# SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, USER_ID
# FROM ONLINE_SALE 
# GROUP BY YEAR,MONTH