SELECT
  C.CAR_ID,
  C.CAR_TYPE,
  FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100.0)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_Rental_Company_Discount_Plan AS DP
  ON DP.CAR_TYPE = C.CAR_TYPE
 AND DP.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  -- 2022-11-01 ~ 2022-11-30과 겹치는 대여 이력이 "없어야" 가용
  AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE H.CAR_ID = C.CAR_ID
          AND H.START_DATE <= DATE('2022-11-30')
          AND H.END_DATE   >= DATE('2022-11-01')
      )
  -- FEE 범위 (정수부분만 출력 → FLOOR 사용)
  AND FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100.0)) >= 500000
  AND FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100.0)) < 2000000
ORDER BY
  FEE DESC,
  C.CAR_TYPE ASC,
  C.CAR_ID DESC;
