-- 코드를 작성해주세요

# SELECT *
# FROM HR_EMPLOYEES as A
# JOIN HR_GRADE as B on A.EMP_NO = B.EMP_NO

SELECT (B.SCORE) as SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES as A
JOIN (
SELECT EMP_NO, SUM(SCORE) as SCORE
FROM HR_GRADE 
GROUP BY EMP_NO
) as B on A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
ORDER BY B.SCORE DESC
LIMIT 1