-- 코드를 입력하세요

WITH RECURSIVE time_T as (
    
    SELECT 0 as HOUR
    
    
    UNION all
    
    SELECT HOUR + 1 
    FROM time_T
    WHERE HOUR + 1 <= 23
)


SELECT A.HOUR, COUNT(B.DATETIME) as COUNT
FROM time_T as A
left join ANIMAL_OUTS as B on A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR




# SELECT HOUR(DATETIME) as HOUR, COUNT(*) as COUNT
# FROM ANIMAL_OUTS 
# GROUP BY HOUR