-- 코드를 작성해주세요

# SELECT *
# FROM FISH_INFO 

# SELECT B.FISH_COUNT, A.FISH_NAME
# FROM FISH_NAME_INFO as A
# JOIN (
# SELECT FISH_TYPE, COUNT(ID) as FISH_COUNT
# FROM FISH_INFO 
# GROUP BY FISH_TYPE
# ) as B on A.FISH_TYPE = B.FISH_TYPE
# ORDER BY B.FISH_COUNT DESC

SELECT COUNT(*) as FISH_COUNT, B.FISH_NAME
FROM FISH_INFO as A
JOIN FISH_NAME_INFO as B on A.FISH_TYPE = B.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC