-- 코드를 작성해주세요
WITH base as (
 SELECT YEAR(DIFFERENTIATION_DATE) as y, ID, SIZE_OF_COLONY,
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) as max_size
    FROM ECOLI_DATA 
)

SELECT y  as `YEAR`, (max_size - SIZE_OF_COLONY) as YEAR_DEV, ID
FROM base  
ORDER BY `YEAR`, YEAR_DEV