-- 코드를 작성해주세요
WITH year_max_size as (
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as max_size
FROM ECOLI_DATA 
GROUP BY YEAR
)


SELECT B.YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY as YEAR_DEV, A.ID
FROM ECOLI_DATA as A
JOIN YEAR_MAX_SIZE as B on YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR ASC, YEAR_DEV ASC
