-- 코드를 작성해주세요
WITH TEMP as (
SELECT YEAR(DIFFERENTIATION_DATE) as year, MAX(SIZE_OF_COLONY) as size
FROM ECOLI_DATA 
GROUP BY year
)
    
    
SELECT B.YEAR, B.SIZE-A.SIZE_OF_COLONY as YEAR_DEV, A.ID
FROM ECOLI_DATA  as A
JOIN TEMP as B on YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR,YEAR_DEV ASC;