-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, SUM(A.PRICE*B.SALES_AMOUNT) as SALES
FROM PRODUCT as a
JOIN OFFLINE_SALE  as B on A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE ASC