-- 코드를 입력하세요
# SELECT *
# FROM PRODUCT AS a
# JOIN OFFLINE_SALE AS B on A.PRODUCT_ID = B.PRODUCT_ID

WITH TEMP as (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as TOTAL
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT A.PRODUCT_CODE, A.PRICE*B.TOTAL as SALES
FROM PRODUCT as A
JOIN TEMP as B on A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, A.PRODUCT_CODE ASC