

SELECT B.USER_ID, B.NICKNAME, CONCAT_WS(' ',B.CITY,B.STREET_ADDRESS1,B.STREET_ADDRESS2) as `전체주소`, 
CONCAT(SUBSTRING(B.TLNO,1,3),'-',SUBSTRING(B.TLNO,4,4),'-',SUBSTRING(B.TLNO,8,4)) as `전화번호`
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_USER  as B on A.WRITER_ID = B.USER_ID
WHERE A.WRITER_ID in (
SELECT C.WRITER_ID
FROM USED_GOODS_BOARD as C
GROUP BY C.WRITER_ID
HAVING COUNT(C.WRITER_ID) >= 3
)
GROUP BY B.USER_ID
ORDER BY B.USER_ID DESC