-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME,CONCAT_WS(' ',B.CITY,B.STREET_ADDRESS1,B.STREET_ADDRESS2) as `전체주소`,
CONCAT(SUBSTRING(TLNO,1,3),'-',SUBSTRING(TLNO,4,4),'-',SUBSTRING(TLNO,8,4)) as `전화번호`
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_USER  as B on A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(A.WRITER_ID) >= 3
ORDER BY B.USER_ID DESC