-- 코드를 입력하세요

WITH COUNTS as (
SELECT COUNT(*) as COUNTS
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
)


SELECT YEAR(A.SALES_DATE) as YEAR, MONTH(A.SALES_DATE) as MONTH, COUNT(DISTINCT A.USER_ID) as PURCHASED_USERS, ROUND(COUNT(DISTINCT A.USER_ID)/C.COUNTS,1) as PUCHASED_RATIO
FROM ONLINE_SALE as A
JOIN USER_INFO as B on A.user_ID = B.USER_ID
JOIN COUNTS as C on 1 = 1
WHERE YEAR(B.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC