-- 코드를 입력하세요
# WITH YEAR_JOINED as (
# SELECT YEAR(JOINED) as YEAR, COUNT(USER_ID) as TOTAL
# FROM USER_INFO 
# WHERE YEAR(JOINED) = '2021'
# GROUP BY YEAR
# )

# SELECT DISTINCT YEAR(O.SALES_DATE) as YEAR, MONTH(O.SALES_DATE) as MONTH, COUNT(DISTINCT U.USER_ID) as PURCHASED_USERS,
# ROUND(COUNT(U.USER_ID)/Y.TOTAL,1) as PUCHASED_RATIO
# FROM USER_INFO as U
# JOIN ONLINE_SALE as O on U.USER_ID = O.USER_ID
# JOIN YEAR_JOINED as Y on YEAR(U.JOINED) = Y.YEAR
# WHERE YEAR(U.JOINED) = '2021'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH


WITH YEAR_JOINED AS (
  SELECT COUNT(USER_ID) AS TOTAL
  FROM USER_INFO
  WHERE YEAR(JOINED) = 2021
)
SELECT 
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID)/Y.TOTAL,1) AS PURCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O
  ON U.USER_ID = O.USER_ID
JOIN YEAR_JOINED AS Y
  ON 1=1  -- 단순 CTE 참조
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR, MONTH;
