-- 코드를 입력하세요
WITH TEMP as (
    SELECT COUNT(DISTINCT USER_ID) as TOTAL
    FROM USER_INFO 
    WHERE YEAR(JOINED) = '2021'
), TEMP2 as (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)


SELECT YEAR(A.SALES_DATE) as `YEAR`, MONTH(A.SALES_DATE) as `MONTH`, COUNT(DISTINCT A.USER_ID) as PURCHASED_USERS, 
ROUND((COUNT(DISTINCT A.USER_ID)/B.TOTAL),1) as PUCHASED_RATIO
FROM ONLINE_SALE as A
JOIN TEMP as B 
WHERE A.USER_ID IN (SELECT USER_ID FROM TEMP2)
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE) ASC

