-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_TABLE AS (
    -- 1세대: PARENT_ID IS NULL
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 부모의 세대 +1 = 자식 세대
    SELECT C.ID, P.GENERATION + 1
    FROM ECOLI_DATA C
    JOIN GENERATION_TABLE P ON C.PARENT_ID = P.ID
)
SELECT 
    COUNT(*) AS COUNT,
    G.GENERATION
FROM GENERATION_TABLE G
LEFT JOIN ECOLI_DATA C ON C.PARENT_ID = G.ID
WHERE C.ID IS NULL   -- 자식이 없는 경우
GROUP BY G.GENERATION
ORDER BY G.GENERATION;
