-- 코드를 작성해주세요
with recursive temp as (
    SELECT ID,PARENT_ID, 1 as generation
    FROM ECOLI_DATA 
    WHERE PARENT_ID is NULL
    
    union all
    
    SELECT A.ID, A.PARENT_ID, B.GENERATION + 1 as GENERATION
    FROM ECOLI_DATA as A
    JOIN temp as B on a.PARENT_ID = B.ID

)

SELECT COUNT(*) as COUNT, GENERATION
FROM temp as a
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC