-- 코드를 입력하세요
SELECT b.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(s.SALES * B.PRICE) as TOTAL_SALES
FROM BOOK_SALES as s
JOIN BOOK as b on s.BOOK_ID = b.BOOK_ID
JOIN AUTHOR as a on b.AUTHOR_ID = a.AUTHOR_ID
WHERE SALES_DATE BETWEEN '2022-01-1' and '2022-01-31'
GROUP BY b.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY b.AUTHOR_ID ASC, B.CATEGORY DESC
