-- 코드를 입력하세요
# SELECT *
# FROM BOOK_SALES 
# WHERE YEAR(SALES_DATE) = '2022' and MONTH(SALES_DATE) = '01'

SELECT A.AUTHOR_ID,B.AUTHOR_NAME,A.CATEGORY, SUM(C.SALES*A.PRICE) as TOTAL_SALES
FROM BOOK as A
JOIN AUTHOR as B on A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES as C on A.BOOK_ID = C.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' and MONTH(SALES_DATE) = '01'
GROUP BY A.CATEGORY,B.AUTHOR_NAME,A.AUTHOR_ID
ORDER BY A.AUTHOR_ID,A.CATEGORY DESC