-- 코드를 입력하세요

WITH SALES as (
SELECT BOOK_ID, SALES
FROM BOOK_SALES 
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    )
    

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) as TOTAL_SALES
FROM BOOK as A
JOIN AUTHOR  as B on A.AUTHOR_ID = B.AUTHOR_ID
JOIN SALES as C on A.BOOK_ID = C.BOOK_ID
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC , A.CATEGORY DESC