-- 코드를 입력하세요
# SELECT *
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1),1) as AVERAGE_DURATION
# SELECT car_ID,START_DATE,END_DATE,DATEDIFF(END_DATE, START_DATE)+1
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE DATEDIFF(END_DATE, START_DATE) + 1 >= 7
# ORDER BY CAR_ID
GROUP BY CAR_ID 
    HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
