WITH SIZE as (
SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) as SIZE
FROM ECOLI_DATA
)
    

SELECT A.ID, 
    CASE B.SIZE
        WHEN '1' THEN 'CRITICAL'
        WHEN '2' THEN 'HIGH'
        WHEN '3' THEN 'MEDIUM'
    ELSE 'LOW'
    END as COLONY_NAME
FROM ECOLI_DATA as A
JOIN SIZE as B on A.ID = B.ID
ORDER BY A.ID
