-- 코드를 작성해주세요
# SELECT ID,
#     CASE NTILE_COL
#         WHEN 1 THEN 'CRITICAL'
#         WHEN 2 THEN 'HIGH'
#         WHEN 3 THEN 'MEDIUM'
#         WHEN 4 THEN 'LOW'
#     END as COLONY_NAME
# FROM (
#  SELECT ID, SIZE_OF_COLONY,
#     NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) as NTILE_COL
# FROM ECOLI_DATA 
# ) AS SUB
# ORDER BY ID



# SELECT ID, 
#     CASE NTILE_COL
#         WHEN 1 THEN 'CRITICAL'
#         WHEN 2 THEN 'HIGH'
#         WHEN 3 THEN 'MEDIUM'
#         WHEN 4 THEN 'LOW'
#     END as COLONY_NAME
# FROM (
#     SELECT ID, SIZE_OF_COLONY,
#     NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) as NTILE_COL
#     FROM ECOLI_DATA 
# ) AS SUB
# ORDER BY ID


SELECT ID,
    CASE NTILE_COL
    WHEN 1 THEN 'CRITICAL'
    WHEN 2 THEN 'HIGH'
    WHEN 3 THEN 'MEDIUM'
    WHEN 4 THEN 'LOW'
    END
    as COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY,
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) as NTILE_COL
    FROM ECOLI_DATA
) as SUB
ORDER BY ID



















