-- 코드를 입력하세요
WITH BOARDS AS (
SELECT *
FROM USED_GOODS_BOARD as B
ORDER BY VIEWS DESC
limit 1
)


SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) as FILE_PATH
FROM BOARDS as B
JOIN USED_GOODS_FILE as F on B.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC