-- 코드를 입력하세요
WITH TEMP as (
    SELECT *
    FROM USED_GOODS_BOARD 
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/',A.BOARD_ID,'/',B.FILE_ID,B.FILE_NAME,B.FILE_EXT) as FILE_PATH
FROM TEMP as A
JOIN USED_GOODS_FILE  as B on A.BOARD_ID = B.BOARD_ID
ORDER BY B.FILE_ID DESC
