-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT as A
JOIN DOCTOR as D on A.MDDR_ID = D.DR_ID
JOIN PATIENT as P on A.PT_NO = P.PT_NO
WHERE DATE(A.APNT_YMD) = '2022-04-13' and A.MCDP_CD = 'CS' and A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD