-- 코드를 작성해주세요
WITH CODES as (
SELECT CODE
FROM SKILLCODES  
WHERE NAME in ('Python', 'C#')
)

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS as D
JOIN CODES as C on D.SKILL_CODE &  C.CODE > 0
ORDER BY  D.ID