-- 코드를 입력하세요
WITH TEMP as (
SELECT CAR_ID,CAR_TYPE,DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE = '트럭'
)
    
# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  as A
# JOIN TEMP AS B on A.CAR_ID = B.CAR_ID
,TEMP2 as (
SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE,
    CASE
        WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
    END as DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM TEMP)
)
    
SELECT A.HISTORY_ID, 
    CASE
        WHEN A.DURATION_TYPE IS NULL THEN (DATEDIFF(END_DATE,START_DATE)+1) *B.DAILY_FEE
        ELSE (1-C.discount_rate/100)*B.DAILY_FEE *(DATEDIFF(END_DATE,START_DATE)+1)
    END as FEE
FROM TEMP2 AS A
JOIN TEMP AS B on A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  as C on A.DURATION_TYPE = C.DURATION_TYPE and B.CAR_TYPE = C.CAR_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC