-- 코드를 입력하세요
# SELECT B.HISTORY_ID,
#     CASE 
#     WHEN (END_DATE - START_DATE) >= 90 THEN FLOOR((100-(
#         SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE LIKE('%90%') and CAR_TYPE = '트럭'))*A.DAILY_FEE)
#     WHEN (END_DATE - START_DATE) >= 30 THEN FLOOR((100-(
#         SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE LIKE('%30%') and CAR_TYPE = '트럭'))*A.DAILY_FEE)
#     WHEN (END_DATE - START_DATE) >= 7 THEN FLOOR((100-(
#         SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE LIKE('%7%') and CAR_TYPE = '트럭'))*A.DAILY_FEE)
#     ELSE
#         A.DAILY_FEE
#     END as FEE
# FROM CAR_RENTAL_COMPANY_CAR  as A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY  as B on A.CAR_ID = B.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as C on A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, B.HISTORY_ID DESC


# # SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE LIKE('%90%') and CAR_TYPE = '트럭'

SELECT 
    B.HISTORY_ID,
    FLOOR(
        A.DAILY_FEE 
        * (DATEDIFF(B.END_DATE, B.START_DATE) + 1) 
        * (100 - CASE 
            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90 THEN C90.DISCOUNT_RATE
            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 30 THEN C30.DISCOUNT_RATE
            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 7  THEN C7.DISCOUNT_RATE
            ELSE 0
          END
        ) / 100
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
    ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C7
    ON A.CAR_TYPE = C7.CAR_TYPE AND C7.DURATION_TYPE = '7일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C30
    ON A.CAR_TYPE = C30.CAR_TYPE AND C30.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C90
    ON A.CAR_TYPE = C90.CAR_TYPE AND C90.DURATION_TYPE = '90일 이상'
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, B.HISTORY_ID DESC;
