-- 코드를 작성해주세요

SELECT B.DEPT_ID, B.DEPT_NAME_EN, ROUND(SUM(A.SAL)/COUNT(A.SAL),0) as AVG_SAL
FROM HR_EMPLOYEES as A
JOIN HR_DEPARTMENT as B on A.DEPT_ID = B.DEPT_ID
GROUP BY B.DEPT_ID, B.DEPT_NAME_EN
ORDER BY AVG_SAL DESC