-- 코드를 작성해주세요
SELECT
    CASE 
        WHEN MAX(CASE WHEN s.CATEGORY='Front End' THEN 1 ELSE 0 END) = 1
             AND MAX(CASE WHEN s.NAME='Python' THEN 1 ELSE 0 END) = 1 THEN 'A'
        WHEN MAX(CASE WHEN s.NAME='C#' THEN 1 ELSE 0 END) = 1 THEN 'B'
        WHEN MAX(CASE WHEN s.CATEGORY='Front End' THEN 1 ELSE 0 END) = 1 THEN 'C'
    END AS GRADE,
    d.ID,
    d.EMAIL
FROM DEVELOPERS d
JOIN SKILLCODES s ON d.SKILL_CODE & s.CODE > 0
GROUP BY d.ID, d.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, d.ID;
