-- 코드를 작성해주세요

SELECT  
    CASE
        WHEN max(CASE WHEN B.CATEGORY = 'Front End'THEN 1 ELSE 0 END) and max(CASE WHEN B.NAME='Python' THEN 1 ELSE 0 END) THEN            'A'
        WHEN max(CASE WHEN B.NAME = 'C#' THEN 1 ELSE 0 END) THEN 'B'
        WHEN max(CASE WHEN B.CATEGORY = 'Front End' THEN 1 ELSE 0 END) THEN 'C'
    END as GRADE
    , A.ID, A.EMAIL
FROM DEVELOPERS AS A
JOIN SKILLCODES AS B on A.SKILL_CODE & B.CODE > 0
GROUP BY A.ID, A.EMAIL
HAVING GRADE is NOT NULL
ORDER BY GRADE, A.ID
