-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.TOTAL_SALES) as TOTAL_SALES
FROM BOOK as A
JOIN (
SELECT BOOK_ID, SUM(SALES) as TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE BETWEEN '2022-01-01' and '2022-01-31'
GROUP BY BOOK_ID
) as B on A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY