-- 코드를 입력하세요
WITH TEMP as (
SELECT FOOD_TYPE, max(FAVORITES) as FAVORITES
FROM REST_INFO 
GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO as A
JOIN TEMP as B on A.FAVORITES = B.FAVORITES and A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC