-- 코드를 입력하세요
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME,A.FAVORITES
FROM REST_INFO as A
JOIN (
SELECT FOOD_TYPE, max(FAVORITES) as FAVORITES
FROM REST_INFO 
GROUP BY FOOD_TYPE
) as B on A.FAVORITES = B.FAVORITES and A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY FOOD_TYPE DESC

# SELECT FOOD_TYPE, FAVORITES
# FROM REST_INFO
# ORDER BY FAVORITES DESC