-- 코드를 작성해주세요
WITH MAX_LENGTH as(
    SELECT FISH_TYPE, max(LENGTH) as LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT A.ID, B.FISH_NAME, A.LENGTH 
FROM FISH_INFO as A
JOIN FISH_NAME_INFO as B on A.FISH_TYPE = B.FISH_TYPE
JOIN MAX_LENGTH as C on A.FISH_TYPE = C.FISH_TYPE
WHERE A.LENGTH = C.LENGTH
ORDER BY ID ASC