-- 코드를 입력하세요
WITH TEMP as (
SELECT WRITER_ID, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD 
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
    )

SELECT A.WRITER_ID, B.NICKNAME, A.TOTAL_SALES
FROM TEMP as A
JOIN USED_GOODS_USER  as B on A.WRITER_ID = B.USER_ID
ORDER BY A.TOTAL_SALES ASC
