-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER as A
JOIN (
SELECT WRITER_ID,  SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
    ) as B on A.USER_ID = B.WRITER_ID
WHERE B.TOTAL_SALES >= 700000
ORDER BY B.TOTAL_SALES