-- 코드를 작성해주세요
WITH TEMP as (
SELECT *
FROM ECOLI_DATA 
WHERE PARENT_ID IS NULL
)


SELECT ID
FROM ECOLI_DATA 
WHERE PARENT_ID IN (
    SELECT A.ID
    FROM ECOLI_DATA as a
    JOIN TEMP as b on a.PARENT_ID = b.ID
)
ORDER BY ID ASC