-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF 
GROUP BY FLAVOR) as A

JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) as B on A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
limit 3;