-- 코드를 입력하세요
WITH TEMP1 as (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF
GROUP BY FLAVOR
),
TEMP2 as (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
SELECT A.FLAVOR
FROM TEMP1 as A
JOIN TEMP2 as B on A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY A.TOTAL_ORDER+B.TOTAL_ORDER DESC
LIMIT 3

# SELECT FLAVOR, SUM()
# FROM FIRST_HALF AS A
# JOIN JULY AS B on A.SHIPMENT_ID = B.SHIPMENT_ID
# GROUP BY FLAVOR